// Generated by CoffeeScript 1.9.0
(function() {
  var BD;

  window['BD'] = BD = {};

  BD._dom_from_hint = function(hint) {
    return hint.get(0);
  };


  /* `CS`: Computed Style */

  BD._number_from_cs = function(dom, cs_name) {
    return parseFloat(getComputedStyle(dom)[cs_name]);
  };

  BD.CSS = {};

  BD.css = (function(_this) {
    return function(hint, cs_name) {
      return BD._number_from_cs(BD._dom_from_hint(hint), cs_name);
    };
  })(this);

  $.fn.text_nodes = function() {
    var R;
    R = [];
    this.each(function() {
      var fn;
      fn = arguments.callee;
      return ($(this)).contents().each(function() {
        if (this.nodeType === 3) {
          return R.push(this);
        } else {
          return fn.apply($(this));
        }
      });
    });
    return $(R);
  };

}).call(this);
