// Generated by CoffeeScript 1.9.0
(function() {
  var CND, TEMPLATES, badge, html_route, locator, method_name, methods_and_locators, njs_fs, njs_path, rpr, urge, _i, _len, _ref;

  njs_path = require('path');

  njs_fs = require('fs');

  CND = require('cnd');

  rpr = CND.rpr.bind(CND);

  badge = '眀快排字机/generate-html';

  urge = CND.get_logger('urge', badge);

  TEMPLATES = require('./TEMPLATES');

  methods_and_locators = ['layout', njs_path.join(__dirname, './index.html'), 'test', njs_path.join(__dirname, './test.html')];

  html_route = html_locator.slice(__dirname.length);

  for (_i = 0, _len = methods_and_locators.length; _i < _len; _i++) {
    _ref = methods_and_locators[_i], method_name = _ref[0], locator = _ref[1];
    njs_fs.writeFileSync(locator, TEMPLATES[method_name](), {
      encoding: 'utf-8'
    });
    urge('wrote ' + html_locator);
  }

}).call(this);
