// Generated by CoffeeScript 1.9.0
(function() {
  var CND, MKTS, alert, app, badge, debug, echo, help, info, log, rpr, urge, warn, whisper, ƒ;

  CND = require('cnd');

  rpr = CND.rpr.bind(CND);

  badge = '眀快排字机/MKTS';

  log = CND.get_logger('plain', badge);

  info = CND.get_logger('info', badge);

  alert = CND.get_logger('alert', badge);

  debug = CND.get_logger('debug', badge);

  warn = CND.get_logger('warn', badge);

  urge = CND.get_logger('urge', badge);

  whisper = CND.get_logger('whisper', badge);

  help = CND.get_logger('help', badge);

  echo = CND.echo.bind(CND);

  app = null;

  MKTS = this;

  ƒ = function(x, precision) {
    if (precision == null) {
      precision = 2;
    }
    return x.toFixed(precision);
  };

  module.exports = function(_app) {
    app = _app;
    return MKTS;
  };

  this.ZOOM = {};

  this.ZOOM._get_zoom_levels = (function(_this) {
    return function() {
      var R, idx, match, matcher, matrix_txt;
      R = [];
      matcher = /[-.e0-9]+/g;
      idx = -1;
      matrix_txt = app['zoomer'].css('transform');
      while ((match = matcher.exec(matrix_txt)) != null) {
        idx += 1;
        if (idx === 0 || idx === 3) {
          R.push(parseFloat(match[0]));
        }
      }
      return R;
    };
  })(this);

  this.ZOOM.to_delta = (function(_this) {
    return function(delta) {
      var scale_x, scale_y, _ref;
      _ref = _this.ZOOM._get_zoom_levels(), scale_x = _ref[0], scale_y = _ref[1];
      scale_x += delta;
      scale_y += delta;
      app['zoomer'].css('transform', "matrix(" + scale_x + ", 0, 0, " + scale_y + ", 0, 0)");
      return help("zoomed to [ " + (ƒ(scale_x)) + ", " + (ƒ(scale_y)) + ", ]");
    };
  })(this);

  this.ZOOM.by = (function(_this) {
    return function(factor) {
      var center_x, center_y, scale_x, scale_y, _ref, _ref1;
      _ref = app['mouse-position'], center_x = _ref[0], center_y = _ref[1];
      _ref1 = _this.ZOOM._get_zoom_levels(), scale_x = _ref1[0], scale_y = _ref1[1];
      scale_x *= factor;
      scale_y *= factor;
      app['zoomer'].css('transform', "matrix(" + scale_x + ", 0, 0, " + scale_y + ", 0, 0)");
      return help("zoomed to [ " + (ƒ(scale_x)) + ", " + (ƒ(scale_y)) + ", ]");
    };
  })(this);

  this.ZOOM.to = (function(_this) {
    return function(scale_x, scale_y) {
      if (scale_y == null) {
        scale_y = null;
      }
      if (scale_y == null) {
        scale_y = scale_x;
      }
      app['zoomer'].css('transform', "matrix(" + scale_x + ", 0, 0, " + scale_y + ", 0, 0)");
      return help("zoomed to [ " + (ƒ(scale_x)) + ", " + (ƒ(scale_y)) + ", ]");
    };
  })(this);

  this.actions = {};

  this.actions['demo'];

  this.actions['demo-1'];

  this.actions['print'];

  this.actions['print-preview'];

  this.actions['open'];

  this.actions['save'];

  this.actions['save-as'];

  this.actions['view-test'] = (function(_this) {
    return function() {
      return window.location.href = './test.html';
    };
  })(this);

}).call(this);
