// Generated by CoffeeScript 1.9.0
(function() {
  var CND, badge, debug, help, info, rpr, warn, xcss_rules;

  CND = require('cnd');

  rpr = CND.rpr;

  badge = 'MKTS/mingkwai-styles-fix';

  warn = CND.get_logger('warn', badge);

  help = CND.get_logger('help', badge);

  debug = CND.get_logger('debug', badge);

  info = CND.get_logger('info', badge);

  xcss_rules = require('./xcss-rules');

  this.rules_from_node = function(app, node) {
    var R, idx, idxs, property, rules, selector, selectors, value, _i, _len, _ref;
    if (node.length !== 1) {
      throw new Error("argument `node` must contain single element, has " + node.length);
    }
    R = {};
    selectors = xcss_rules['%selectors'], rules = xcss_rules.rules;

    /* TAINT selectors not properly ordered */
    for (selector in selectors) {
      idxs = selectors[selector];
      if (!node.is(selector)) {
        continue;
      }
      for (_i = 0, _len = idxs.length; _i < _len; _i++) {
        idx = idxs[_i];
        _ref = rules[idx], property = _ref.property, value = _ref.value;
        R[property] = value;
      }
    }
    return R;
  };

}).call(this);
