#!/usr/bin/env bash

DIR="$( cd "$( dirname "${BASH_SOURCE[0]}" )" && pwd )"
cd $DIR


coffee -o mingkwai.app/Contents/Resources/app.nw/lib -c mingkwai.app/Contents/Resources/app.nw/src && \
git add --all && \
git commit -m "autocommit"
git push -u origin master
echo

# doctoc README.md && \
# coffeedoc -o doc src && \
