#! /usr/bin/env bash

DIR="$( cd "$( dirname "${BASH_SOURCE[0]}" )" && pwd )"
cd $DIR
# ./build && open mingkwai.app
# ./build && nw ./mingkwai.app/Contents/Resources/app.nw
./mingkwai.app/Contents/MacOS/nwjs ./mingkwai.app/Contents/Resources/app.nw




